void moduloAgenda(void);
void telaAgenda(char[]);
void mostragemAgendaCompromissos(void);
void mostragemAgendaAvisos(void);
char agendaFuncionario(void);
char agendaGerencia(void);
void agendaGerenciaCodigo(void);
void navegacaoAgendaGerencia(void);
void navegacaoAgendaFuncionarios(void);